title: OpenCV Python Doc
description: Site dedicated to documenting the OpenCV Python bindings
theme: just-the-docs

url: https://engle212.github.io/opencv-python-doc

aux_links:
  Template Repository: https://github.com/engle212/opencv-python-doc
